language: node_js
node_js:
  - "node"
install:
  - npm install mocha
  - npm install enzyme
  - npm install enzyme-adapter-react-16
  - npm install babel-core
  - npm install babel-preset-react
  - npm install
