language: node_js
node_js:
  - "node"
install:
  - npm install mocha
  - npm install enzyme
  - npm install babel-core
  - npm install babel-preset-react
  - npm install
script:
  - npm test --imports/ui/*.js
