language: node_js
node_js:
  - "node"
install:
  # Install meteor
  - curl https://install.meteor.com/ | sh
  # Add meteor to path (instead of asking for sudo in the Travis container)
  # We can then use the faster container infrastructure - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
  - export PATH=$HOME/.meteor:$PATH
  - meteor npm install
  - meteor npm install mocha --save-dev
  - meteor npm install enzyme --save-dev
  - meteor npm install enzyme-adapter-react-16 --save-dev
  - meteor npm install babel-core --save-dev
  - meteor npm install babel-preset-env --save-dev
  - meteor npm install babel-preset-react --save-dev
  - meteor npm install babel-polyfill --save-dev
  - meteor add ecmascript
  - meteor add meteortesting:mocha
  - meteor npm install chai --save-dev
script:
- meteor test --driver-package meteortesting:mocha

cache:
  directories:
    - node_modules
